server:
  port: 8085

products:
  number: 5000

spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
